### ISSUE TITLE
@ symbol path, prettier 세팅 및 Header 및 Discom 레이아웃

### ISSUE THREAD

**Issue by JitHoon** [JitHoon/dicom-viewer#1]
## Description

nav bar가 있는 header와 DICOM 이미지를 담을 main 영역의 레이아웃

## Todo

- [x] @ symbol path 세팅
- [x] prettier 세팅
- [x] Header 레이아웃 작업
- [x] Discom 레이아웃 작업
